name: build

on:
  push:
    branches: [ "oneUI4.1" ]
  pull_request:
    branches: [ "oneUI4.1" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Build
        run: ./build.sh d2s 
        
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ github.workspace }}/build/
