name: build

on:
  push:
    branches: [ "oneui5_davinci" ]
  pull_request:
    branches: [ "oneui5_davinci" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Setting up the environment
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install build-essential gcc-aarch64-linux-gnu -y

      - name: Build
        run: ./build.sh d2x
        
      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact/
