name: build

on:
  push:
    branches: [ "kernelsu" ]
  pull_request:
    branches: [ "kernelsu" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Setting up the environment
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install build-essential gcc-aarch64-linux-gnu -y
  
      - name: Setup KernelSU
        run: |
          if [ -d "./KernelSU" ]; then
            rm -rf "./KernelSU"
          fi
          if [ -d "./drivers/kernelsu" ]; then
            rm -rf "./drivers/kernelsu"
          fi
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
          wget -q "https://raw.githubusercontent.com/Star-Seven/android_kernel_samsung_beyondlte/kernelsu/kernelsu.patch" -O KernelSU.patch
          git apply ./KernelSU.patch

      - name: Build
        run: ./build.sh d2xks
        
      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ github.workspace }}/build/
