name: build

on:
  push:
    branches: [ "oneui5_davinci" ]
  pull_request:
    branches: [ "oneui5_davinci" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Setting up the environment
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install build-essential gcc-aarch64-linux-gnu -y
	  
      - name: Setup KernelSU
        run: |
          if [ -d "./KernelSU" ]; then
            rm -rf "./KernelSU"
          fi
          if [ -d "./drivers/kernelsu" ]; then
            rm -rf "./drivers/kernelsu"
          fi
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
          wget -q "https://raw.githubusercontent.com/Star-Seven/samsung-exynos9820/kernelsu/kernelsu.patch" -O KernelSU.patch
          git apply ./KernelSU.patch
          model=$(echo "${{ matrix.model }}" | cut -d ',' -f 1)
          case $model in
            G970F|G973F|G975F)
              config=exynos9820-beyond0lte_defconfig
              ;;
            G977B)
              config=exynos9820-beyondx_defconfig
              ;;
            G977N)
              config=exynos9820-beyondxks_defconfig
              ;;
            N975F)
              config=exynos9820-d2s_defconfig
              ;;
            N976B)
              config=exynos9820-d2x_defconfig
              ;;
            N971N)
              config=exynos9820-d1x_defconfig
              ;;
            N976N)
              config=exynos9820-d2xks_defconfig
              ;;
          esac
          echo -e "CONFIG_KSU=y" >> arch/arm64/configs/$config
          echo -e "CONFIG_OVERLAY_FS=y" >> arch/arm64/configs/$config
          echo -e "CONFIG_OVERLAYFS=y" >> arch/arm64/configs/$config
          echo -e "CONFIG_FS_OVERLAYFS=y" >> arch/arm64/configs/$config

      - name: Build
        run: ./build.sh d2x
        
      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ github.workspace }}/build/
