name: Makefile CI

on:
  push:
    branches: [ "oneui5_davinci" ]
  pull_request:
    branches: [ "oneui5_davinci" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Set Current Date
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Sao_Paulo"

      - name: Setting up the environment
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install build-essential gcc-aarch64-linux-gnu -y

      - name: Build
        run: ./build.sh
        
      - name: build
        uses: actions/upload-build@v2
        with:
          name: build
          path: ${{ github.workspace }}/build/
